// MIT License
//
// Copyright (c) 2024 Jacque-Copy Contributors

import Foundation
import AppKit

/// Manages low-level NSPasteboard operations for reading, writing, and
/// preserving all available pasteboard representations.
///
/// This is the core bridge between the system pasteboard and Jacque-Copy's
/// internal clipboard storage. It handles the critical pasteboard swap
/// operations that make the dual clipboard possible.
public final class PasteboardManager {

    // MARK: - Singleton

    public static let shared = PasteboardManager()

    // MARK: - Properties

    /// The system pasteboard.
    private let pasteboard = NSPasteboard.general

    /// Tracks the last observed change count to detect external clipboard changes.
    private var lastChangeCount: Int = NSPasteboard.general.changeCount

    /// Lock for thread-safe pasteboard operations.
    private let operationLock = NSLock()

    /// Types considered sensitive and should be excluded from storage.
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.1password",
        "org.nspasteboard.Transient"
    ]

    // MARK: - Initialization

    private init() {
        lastChangeCount = pasteboard.changeCount
    }

    // MARK: - Public Clipboard Operations

    /// Captures the entire current contents of the system pasteboard as a ClipboardItem.
    /// - Returns: A ClipboardItem with all available representations, or nil if empty.
    public func captureCurrentPasteboard() -> ClipboardItem? {
        operationLock.lock()
        defer { operationLock.unlock() }

        guard let types = pasteboard.types, !types.isEmpty else {
            return nil
        }

        var representations: [String: Data] = [:]

        for type in types {
            // Skip excluded/sensitive types
            guard !Self.excludedTypes.contains(type.rawValue) else {
                continue
            }

            // Attempt to read data for this type
            if let data = pasteboard.data(forType: type) {
                representations[type.rawValue] = data
            }
            // Handle file promises and other lazy types
            else if type.rawValue.contains("file") || type.rawValue.contains("FilenamesPboardType") {
                if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL] {
                    for url in urls {
                        if let bookmarkData = try? url.bookmarkData(
                            options: .withSecurityScope,
                            includingResourceValuesForKeys: nil,
                            relativeTo: nil
                        ) {
                            representations[type.rawValue] = bookmarkData
                        }
                    }
                }
            }
        }

        guard !representations.isEmpty else {
            return nil
        }

        let preview = ClipboardItem.generatePreview(from: representations)
        let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        return ClipboardItem(
            id: UUID(),
            preview: preview,
            capturedAt: Date(),
            sourceApplication: sourceApp,
            representations: representations,
            isPinned: false,
            isFavorite: false,
            tags: []
        )
    }

    /// Writes a ClipboardItem's representations back to the system pasteboard.
    /// This is used during the paste swap operation.
    /// - Parameter item: The clipboard item to restore to the pasteboard.
    public func writeToPasteboard(_ item: ClipboardItem) {
        operationLock.lock()
        defer { operationLock.unlock() }

        pasteboard.clearContents()

        let pasteboardItems = item.representations.compactMap { (typeString, data) -> NSPasteboardItem? in
            let pbItem = NSPasteboardItem()
            let type = NSPasteboard.PasteboardType(typeString)
            pbItem.setData(data, forType: type)
            return pbItem
        }

        pasteboard.writeObjects(pasteboardItems)
    }

    /// Reads the current pasteboard contents without modifying it.
    /// Used for detecting clipboard changes.
    /// - Returns: The current change count.
    public var currentChangeCount: Int {
        pasteboard.changeCount
    }

    /// Checks whether the pasteboard has changed since the last observation.
    /// - Returns: True if the pasteboard contents have changed.
    public func hasChanged() -> Bool {
        let current = pasteboard.changeCount
        if current != lastChangeCount {
            lastChangeCount = current
            return true
        }
        return false
    }

    /// Atomically swaps the pasteboard content: saves current content,
    /// writes new content, returns the saved content.
    /// - Parameter newContent: The clipboard item to write.
    /// - Returns: The previous clipboard contents.
    public func atomicSwap(with newContent: ClipboardItem) -> ClipboardItem? {
        operationLock.lock()
        defer { operationLock.unlock() }

        // Capture current content
        let previousContent = captureCurrentPasteboardUnsafe()

        // Write new content
        pasteboard.clearContents()
        let pasteboardItems: [NSPasteboardItem] = newContent.representations.compactMap { (typeString, data) in
            let pbItem = NSPasteboardItem()
            let type = NSPasteboard.PasteboardType(typeString)
            pbItem.setData(data, forType: type)
            return pbItem
        }
        pasteboard.writeObjects(pasteboardItems)

        // Update tracking
        lastChangeCount = pasteboard.changeCount

        return previousContent
    }

    /// Restores clipboard content, reliably writing all representations back.
    /// - Parameter item: The item to restore, or clears the pasteboard if nil.
    public func restorePasteboard(_ item: ClipboardItem?) {
        operationLock.lock()
        defer { operationLock.unlock() }

        pasteboard.clearContents()

        guard let item = item, !item.representations.isEmpty else {
            lastChangeCount = pasteboard.changeCount
            return
        }

        let pasteboardItems: [NSPasteboardItem] = item.representations.compactMap { (typeString, data) in
            let pbItem = NSPasteboardItem()
            let type = NSPasteboard.PasteboardType(typeString)
            pbItem.setData(data, forType: type)
            return pbItem
        }

        pasteboard.writeObjects(pasteboardItems)
        lastChangeCount = pasteboard.changeCount
    }

    // MARK: - Private Helpers

    /// Internal pasteboard capture without lock (caller must hold lock).
    private func captureCurrentPasteboardUnsafe() -> ClipboardItem? {
        guard let types = pasteboard.types, !types.isEmpty else {
            return nil
        }

        var representations: [String: Data] = [:]

        for type in types {
            guard !Self.excludedTypes.contains(type.rawValue) else {
                continue
            }

            if let data = pasteboard.data(forType: type) {
                representations[type.rawValue] = data
            }
        }

        guard !representations.isEmpty else {
            return nil
        }

        let preview = ClipboardItem.generatePreview(from: representations)
        let sourceApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier

        return ClipboardItem(
            id: UUID(),
            preview: preview,
            capturedAt: Date(),
            sourceApplication: sourceApp,
            representations: representations,
            isPinned: false,
            isFavorite: false,
            tags: []
        )
    }

    /// Returns the names of all available types on the pasteboard.
    public var availableTypes: [String] {
        pasteboard.types?.map(\.rawValue) ?? []
    }
}
