// MIT License
//
// Copyright (c) 2024 Jacque-Copy Contributors

#if os(macOS)

import Foundation
import AppKit

/// macOS-specific clipboard provider using NSPasteboard.
final class MacClipboardProvider: ClipboardProvider {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int = NSPasteboard.general.changeCount
    private let operationLock = NSLock()

    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.1password",
        "org.nspasteboard.Transient"
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func captureCurrent() -> [String: Data] {
        operationLock.lock()
        defer { operationLock.unlock() }

        guard let types = pasteboard.types, !types.isEmpty else {
            return [:]
        }

        var representations: [String: Data] = [:]

        for type in types {
            guard !Self.excludedTypes.contains(type.rawValue) else { continue }

            if let data = pasteboard.data(forType: type) {
                representations[type.rawValue] = data
            } else if type.rawValue.contains("file") || type.rawValue.contains("FilenamesPboardType") {
                if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: nil) as? [URL] {
                    for url in urls {
                        if let bookmarkData = try? url.bookmarkData(
                            options: .withSecurityScope,
                            includingResourceValuesForKeys: nil,
                            relativeTo: nil
                        ) {
                            representations[type.rawValue] = bookmarkData
                        }
                    }
                }
            }
        }

        return representations
    }

    func writeRepresentations(_ representations: [String: Data]) {
        operationLock.lock()
        defer { operationLock.unlock() }

        pasteboard.clearContents()
        let items = representations.compactMap { (typeString, data) -> NSPasteboardItem? in
            let pbItem = NSPasteboardItem()
            pbItem.setData(data, forType: NSPasteboard.PasteboardType(typeString))
            return pbItem
        }
        pasteboard.writeObjects(items)
    }

    func hasChanged() -> Bool {
        let current = pasteboard.changeCount
        if current != lastChangeCount {
            lastChangeCount = current
            return true
        }
        return false
    }

    func availableTypes() -> [String] {
        pasteboard.types?.map(\.rawValue) ?? []
    }

    func frontmostApplicationBundleID() -> String? {
        NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    }
}

#endif
